Update jenkins1

diff --git a/jenkins1 b/jenkins1
--- a/jenkins1
+++ b/jenkins1
@@ -5,9 +5,9 @@ properties([
         choice(name: 'GCP_PROJECT_ID', choices: ['hsbc-12609073-peakplatuat-dev', 'project2', 'project3'], defaultValue: 'hsbc-12609073-peakplatuat-dev', description: 'Google Cloud Project'),
         string(name: 'BUILD_SA', defaultValue: 'automation-deployment', description: 'GCP Service Account', trim: true),
         string(name: 'ENVIRONMENT', defaultValue: 'DEV', description: 'GCP Project Environment', trim: true),
-        choice(name: 'TF_MODULE', choices: ['CR-Automation-Servicenow-API'], defaultValue: 'CR-Automation-Servicenow-API', description: 'Terraform Module Location'),
-        choice(name: 'GCP_REGION', choices: ['us-central1'], defaultValue: 'us-central1', description: 'GCP Region'),
-        choice(name: 'TF_ACTION', choices: ['apply', 'plan', 'destroy'], defaultValue: 'apply', description: 'Terraform Action'),
+        choice(name: 'TF_MODULE', choices: ['CR-Automation-Servicenow-API', 'module2', 'module3'], defaultValue: 'CR-Automation-Servicenow-API', description: 'Terraform Module Location'),
+        choice(name: 'GCP_REGION', choices: ['us-central1', 'us-east1', 'us-west1'], defaultValue: 'us-central1', description: 'GCP Region'),
+        choice(name: 'TF_ACTION', choices: ['plan', 'apply', 'destroy'], defaultValue: 'plan', description: 'Terraform Action'),
         booleanParam(name: 'SKIP_CP_CHECK', defaultValue: false, description: 'Skip CR Approval Check')
     ])
 ])
@@ -24,42 +24,74 @@ pipeline {
     }
 
     stages {
-        stage('Terraform Execution') {
+        stage('Check Repo Subdirectories') {
+            steps {
+                script {
+                    echo "Checking if 'gcp_projects' and 'modules' directories exist in Git..."
+                    sh "git ls-tree -r HEAD --name-only | grep -E '^(gcp_projects|modules)/' || echo 'Directories missing or not committed'"
+                }
+            }
+        }
+
+        stage('Setup & Terraform Execution') {
             steps {
                 script {
                     try {
                         def WORKSPACE_DIR = "${env.WORKSPACE}/${PIPELINE_ID}"
-                        def tfVarsFile = "terraform.tfvars"
+                        def tfVarsFile = "${params.ENVIRONMENT}.tfvars"
 
-                        withCredentials([file(credentialsId: "${GCP_SA_KEY_ID}", variable: 'GCP_SA_KEY_FILE'),
-                                         usernamePassword(credentialsId: 'servicenow-api-basic', usernameVariable: 'SNOW_USER', passwordVariable: 'SNOW_PASS')]) {
+                        withCredentials([file(credentialsId: "${GCP_SA_KEY_ID}", variable: 'GCP_SA_KEY_FILE')]) {
+                            withCredentials([file(credentialsId: 'NETRC_CONFIG', variable: 'NETRC_CONFIG_FILE')]) {
+                                sh """
+                                    mkdir -p ${WORKSPACE_DIR}/${params.TF_MODULE}
+                                    cp ${GCP_SA_KEY_FILE} ${WORKSPACE_DIR}/secret-sa.json && chmod 700 ${WORKSPACE_DIR}/secret-sa.json
+                                    cp ${NETRC_CONFIG_FILE} ${WORKSPACE_DIR}/${params.TF_MODULE}/.netrc && chmod 700 ${WORKSPACE_DIR}/${params.TF_MODULE}/.netrc
+                                    cp ${NETRC_CONFIG_FILE} ${terraform_provider_home}/.netrc && chmod 700 ${terraform_provider_home}/.netrc
+                                    cp -r modules/${params.TF_MODULE}/* ${WORKSPACE_DIR}/${params.TF_MODULE}
+                                    cp ${tfVarsFile} ${WORKSPACE_DIR}/${params.TF_MODULE}
+                                    cp main.tf ${WORKSPACE_DIR}/${params.TF_MODULE}
+                                    cp providers.tf ${WORKSPACE_DIR}/${params.TF_MODULE}
+                                    cp outputs.tf ${WORKSPACE_DIR}/${params.TF_MODULE}
+                                    cp variables.tf ${WORKSPACE_DIR}/${params.TF_MODULE}
+                                    cp version.tf ${WORKSPACE_DIR}/${params.TF_MODULE}
+                                    cp backend.tf ${WORKSPACE_DIR}/${params.TF_MODULE}
+                                """
 
-                            sh """
-                                mkdir -p ${WORKSPACE_DIR}
-                                cp -r . ${WORKSPACE_DIR}
-                                cp ${GCP_SA_KEY_FILE} ${WORKSPACE_DIR}/secret-sa.json && chmod 700 ${WORKSPACE_DIR}/secret-sa.json
-                            """
+                                dir("${WORKSPACE_DIR}/${params.TF_MODULE}") {
+                                    withEnv([
+                                        "GOOGLE_APPLICATION_CREDENTIALS=${WORKSPACE_DIR}/secret-sa.json",
+                                        "HOME=${terraform_provider_home}",
+                                        "HTTP_PROXY=http://googleapis-dev.gcp.cloud.uk.hsbc:3128",
+                                        "HTTPS_PROXY=http://googleapis-dev.gcp.cloud.uk.hsbc:3128",
+                                        "NO_PROXY=.hsbc"
+                                    ]) {
+                                        if (params.TF_MODULE == "tfstate-bucket") {
+                                            echo "Using local tfstate for module: ${params.TF_MODULE}"
+                                            sh 'terraform init -upgrade=false -no-color'
+                                        } else {
+                                            sh """
+                                                sed -i 's/.local./backend "gcs" {}/' backend.tf
+                                                terraform init -no-color -force-copy -get=true -lock=true -input=false -backend=true \
+                                                    -backend-config="bucket=${params.GCP_PROJECT_ID}-${params.GCP_REGION}-terraform" \
+                                                    -backend-config="prefix=terraform-${params.TF_MODULE}-${params.ENVIRONMENT}"
+                                            """
+                                        }
 
-                            dir("${WORKSPACE_DIR}") {
-                                withEnv([
-                                    "GOOGLE_APPLICATION_CREDENTIALS=${WORKSPACE_DIR}/secret-sa.json",
-                                    "HOME=${terraform_provider_home}",
-                                    "TF_VAR_servicenow_username=${SNOW_USER}",
-                                    "TF_VAR_servicenow_password=${SNOW_PASS}"
-                                ]) {
-                                    sh 'terraform init -upgrade=false -no-color'
-                                    sh 'terraform validate -no-color'
+                                        sh 'terraform validate -no-color'
+                                        sh "terraform workspace select ${params.ENVIRONMENT} 2>/dev/null || terraform workspace new ${params.ENVIRONMENT}"
 
-                                    if (params.TF_ACTION == "apply") {
-                                        sh "terraform apply -auto-approve -no-color -var-file=${tfVarsFile}"
-                                    } else if (params.TF_ACTION == "plan") {
-                                        sh "terraform plan -out=tfplan -no-color -var-file=${tfVarsFile}"
-                                    } else {
-                                        sh "terraform destroy -auto-approve -no-color -var-file=${tfVarsFile}"
+                                        if (params.TF_ACTION == "apply") {
+                                            sh "terraform apply -auto-approve -no-color -var-file=${tfVarsFile} -var project_id=${params.GCP_PROJECT_ID}"
+                                        } else if (params.TF_ACTION == "plan") {
+                                            sh "terraform plan -out=tfplan -no-color -var-file=${tfVarsFile} -var project_id=${params.GCP_PROJECT_ID}"
+                                        } else {
+                                            sh "terraform destroy -auto-approve -no-color -var-file=${tfVarsFile} -var project_id=${params.GCP_PROJECT_ID}"
+                                        }
+
+                                        env.CR_ID = sh(script: "terraform output -raw cr_id", returnStdout: true).trim()
+                                        echo "Captured CR ID: ${env.CR_ID}"
+                                        echo "CR ID to be checked: ${env.CR_ID}"
                                     }
-
-                                    env.CR_ID = sh(script: "terraform output -raw cr_id", returnStdout: true).trim()
-                                    echo "Captured CR ID: ${env.CR_ID}"
                                 }
                             }
                         }
@@ -70,6 +102,16 @@ pipeline {
                         sh "rm -rf ${env.WORKSPACE}/${PIPELINE_ID}"
                     }
                 }
+            }
+        }
+
+        stage('Debug Info') {
+            steps {
+                script {
+                    echo "Current working directory: ${pwd()}"
+                }
+                sh 'ls -l'
+                sh "ls -l ${env.WORKSPACE}/${PIPELINE_ID}"
             }
         }
 
